[loggers]
keys=root,demo

[handlers]
keys=fileHandler

[formatters]
keys=sampleformatter

[logger_root]
level=DEBUG
handlers=fileHandler


[logger_demo]
level=DEBUG
handlers=fileHandler
qualname=demo
args=('test.log','w')

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=sampleformatter
args=('test.log','a')

[formatter_sampleformatter]
format=%(asctime)s:%(name)s:%(levelname)s:%(message)s
datefmt=%d/%m/%y-%I:%M:%S %p

